### ISSUE TITLE
Compatible gcode sender

### ISSUE THREAD

**Issue by raininja** [Domush/mvCNC-Modern-Vintage-CNC-Firmware#2]
So I'm wondering, with what program can I utilize this code I've built? Are you using something specific?

**Comment by Domush** [comment]
> So I'm wondering, with what program can I utilize this code I've built? Are you using something specific?

I use CNCjs (in marlin mode), which is probably the most compatible Marlin-friendly control software out right now (that I'm aware of)

**Comment by raininja** [comment]
Thanks, I will try that
